export const activity_event = {
  ADMIN_LOG_IN: "ADMIN_LOG_IN",
  RESELLER_LOG_IN: "RESELLER_LOG_IN",
  USER_LOG_IN: "USER_LOG_IN",
  STAFF_LOG_IN: "STAFF_LOG_IN",
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_ACCEPTED: "ORDER_ACCEPTED",
  ORDER_DECLINED: "ORDER_DECLINED",
  ORDER_SHIPPED: "ORDER_SHIPPED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  SUBSCRIPTION_ADDED: "SUBSCRIPTION_ADDED",
  NEW_CAMPAIGN_ADDED: "NEW_CAMPAIGN_ADDED",
  NEW_PRODUCT_ADDED: "NEW_PRODUCT_ADDED",
  NEW_COLLECTION_ADDED: "NEW_COLLECTION_ADDED",
  NEW_TUTORIAL_ADDED: "NEW_TUTORIAL_ADDED",
  NEW_LEAD_ADDED: "NEW_LEAD_ADDED",
  NEW_GROUP_ADDED: "NEW_GROUP_ADDED",
  LEAD_COMPLETED: "LEAD_COMPLETED",
  LEAD_CALLED: "LEAD_CALLED",
  LEAD_CALLING: "LEAD_CALLING",
  LEAD_CONVERTED: "LEAD_CONVERTED",
  RESELLER_WITHDRAW: "RESELLER_WITHDRAW",
  RESELLER_PAYOUT: "RESELLER_PAYOUT",
  WALLET_DEBIT: "WALLET_DEBIT",
  WALLET_CREDIT: "WALLET_CREDIT",
  ADMIN_REGISTERD: "ADMIN_REGISTERD",
  STAFF_REGISTERD: "STAFF_REGISTERD",
};
export const event_description = {
  ADMIN_LOG_IN: "System administrator logs in to manage operations.",
  RESELLER_LOG_IN: "Reseller logs in to access specific features.",
  USER_LOG_IN: "User logs in to explore services and products.",
  STAFF_LOG_IN: "Staff member logs in to perform role-related tasks.",
  ORDER_PLACED: "Customer places an order for products or services.",
  ORDER_ACCEPTED: "System accepts customer's order for processing.",
  ORDER_DECLINED: "System declines customer's order.",
  ORDER_SHIPPED: "Ordered items are shipped for delivery.",
  ORDER_DELIVERED: "Ordered items are successfully delivered.",
  SUBSCRIPTION_ADDED: "User adds a new subscription for regular updates.",
  NEW_CAMPAIGN_ADDED: "New marketing campaign is added to promote products or services.",
  NEW_PRODUCT_ADDED: "New product is added to the platform's catalog.",
  NEW_COLLECTION_ADDED: "New collection of products is added.",
  NEW_TUTORIAL_ADDED: "New tutorial or educational content is added.",
  NEW_LEAD_ADDED: "New potential customer lead is added for follow-up.",
  NEW_GROUP_ADDED: "New group or community is added for user interaction.",
  LEAD_COMPLETED: "Customer lead is successfully completed.",
  LEAD_CALLED: "Lead is contacted via phone for engagement.",
  LEAD_CALLING: "System initiates a call to a potential lead.",
  LEAD_CONVERTED: "Potential lead is successfully converted.",
  RESELLER_WITHDRAW: "Reseller initiates fund withdrawal.",
  RESELLER_PAYOUT: "System processes and completes reseller payout.",
  WALLET_DEBIT: "Funds are deducted from user's wallet for a transaction.",
  WALLET_CREDIT: "Funds are added to user's wallet.",
  ADMIN_REGISTERD: "ADMIN_REGISTERD",
  STAFF_REGISTERD: "STAFF_REGISTERD",
};
