export const lead_status = {
    "OPEN": "OPEN",
    "UNDER_CONNECTION": "UNDER_CONNECTION",
    "FOLLOWUP": "FOLLOWUP",
    "PROSPECTS": "PROSPECTS",
    "ON_HOLD": "ON_HOLD",
    "CANCELLED": "CANCELLED",
    "COMPLETED": "COMPLETED",
    "COMFIRMED": "COMFIRMED"
}
// },
export const lead_source = {
    "WHATSAPP": "WHATSAPP",
    "INSTAGRAM": "INSTAGRAM",
    "SOCIAL_SELLER_WEBSITE": "SOCIAL_SELLER_WEBSITE",
    "YOUTUBE_CHANNEL": "YOUTUBE_CHANNEL",
    "APP": "APP",
    "WEBSITE": "WEBSITE"
}
export const lead_type = {
    "HOT_LEAD": "HOT_LEAD",
    "WARM_LEAD": "WARM_LEAD",
    "COLD_LEAD": "COLD_LEAD",
    "NOT_CONNECTED": "NOT_CONNECTED"
}