export const order_status = {
    NEW: "NEW",
    ACCEPTED: "ACCEPTED",
    DECLINED: "DECLINED",
    PROCESSING: "PROCESSING",
    INTRANSIT: "INTRANSIT",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED",
    PAYOUT_DONE: "PAYOUT_DONE",
    RTO: "RTO",
    RETURN_REQUEST: "RETURN_REQUEST",
    RETURN_ACCEPTED: "RETURN_ACCEPTED",
    RETURN_DECLINED: "RETURN_DECLINED",
    RETURN_RECEIVED: "RETURN_RECEIVED",
    RETURN_PENDING: "RETURN_PENDING"
};