export default {
  Consumer: [
    "Create Address",
    "List User's Address",
    "List All Address",
    "Update Address",
    "Add To Cart",
    "List Consumer cart",
    "Empty cart",
    "Remove Item From Cart",
    "Return custom-courier Product",
    "Create  Lead",
    "Checkout Razorpay Order",
    "Verify Razorpay Order",
    "Checkout Wallet Order",
    "Check Out Subscription",
    "Verify Subscription",
    "Server Fee Check Out Subscription",
    "Server Fee Verify Subscription",
    "Refund Subscription",
    "Create  Support Ticket",
    "Forget Password",
    "Reset Password",
    "Update  User",
    "Register FCM",
    "Withdraw from Wallet",
    "Redirect to Product",
    "Find  Subscriptions",
    "Create account-details",
    "List User's account-details",
    "Update account-details",
    "Delete account-details",
  ],
  Admin: [
    "Create Address",
    "List User's Address",
    "List All Address",
    "Update Address",
  ],
  // Public: [
  //     "Create Address",
  //     "List User's Address",
  //     "List All Address",
  //     "Update Address",
  // ],
  Staff: [
    "Create campaigns",
    "List campaigns",
    "Update campaigns",
    "Delete campaigns",
  ],
};
